= AMQ Streams (KAFKA) on OCP  - Installation Workshop Activities
Steps to install AMQ Streams 1.x on OCP 3.9+
:toc:


Considerations: * So if you have a centralized cluster operator, ????

== Ephemeral AQM Streams Installation
=== Setup Resources for Ephemeral AQM Streams Installation

* Step 1: Create a new Namespece

	oc new-project amq-streams-ephemeral
	oc login -u system:admin

* Step 2: Get the latest version of AMQ Streams CRDs
** Either Download the latest CRDs link:https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?downloadType=distributions&product=jboss.amq.streams[AMQ Streams ]
** *[Selected]* The availble CRDs from this repository link:https://github.com/skoussou/ocp-amq-streams-workshop/tree/master/install_and_examples_0[install_and_examples_0]

* Step 3: Install the CRD (CustomResourceDefinition) objects for AMQ Streams

	cd install_and_examples_0
	sed -i 's/namespace: .*/namespace: amq-streams-ephemeral/' install/cluster-operator/*RoleBinding*.yaml
	oc apply -f install/cluster-operator/

** See here: link:https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#ref-list-of-kafka-cluster-resources-deployment-configuration-kafka[List of resources created as part of Kafka cluster] in the namespace


=== Install AMQ Streams

* Step 1: Install *KAFKA* object
	cd install_and_examples_0
	oc create -f examples/kafka/kafka-ephemeral.yaml

** The *OCP Operators* monitors for certain objects and takes action 

	grep -r kafka.strimzi.io
	cluster-operator/041-Crd-kafkaconnect.yaml:  name: kafkaconnects.kafka.strimzi.io
	cluster-operator/041-Crd-kafkaconnect.yaml:  group: kafka.strimzi.io
	cluster-operator/040-Crd-kafka.yaml:  name: kafkas.kafka.strimzi.io
	cluster-operator/040-Crd-kafka.yaml:  group: kafka.strimzi.io
	cluster-operator/042-Crd-kafkaconnects2i.yaml:  name: kafkaconnects2is.kafka.strimzi.io
	cluster-operator/042-Crd-kafkaconnects2i.yaml:  group: kafka.strimzi.io
	cluster-operator/043-Crd-kafkatopic.yaml:  name: kafkatopics.kafka.strimzi.io
	cluster-operator/043-Crd-kafkatopic.yaml:  group: kafka.strimzi.io
	cluster-operator/031-ClusterRole-strimzi-entity-operator.yaml:  - kafka.strimzi.io
	cluster-operator/031-ClusterRole-strimzi-entity-operator.yaml:  - kafka.strimzi.io
	cluster-operator/045-Crd-kafkamirrormaker.yaml:  name: kafkamirrormakers.kafka.strimzi.io
	cluster-operator/045-Crd-kafkamirrormaker.yaml:  group: kafka.strimzi.io
	cluster-operator/020-ClusterRole-strimzi-cluster-operator-role.yaml:  - kafka.strimzi.io
	cluster-operator/032-ClusterRole-strimzi-topic-operator.yaml:  - kafka.strimzi.io
	cluster-operator/044-Crd-kafkauser.yaml:  name: kafkausers.kafka.strimzi.io
	cluster-operator/044-Crd-kafkauser.yaml:  group: kafka.strimzi.io
	user-operator/02-Role-strimzi-user-operator.yaml:  - "kafka.strimzi.io"
	user-operator/04-Crd-kafkauser.yaml:  name: kafkausers.kafka.strimzi.io
	user-operator/04-Crd-kafkauser.yaml:  group: kafka.strimzi.io
	topic-operator/02-Role-strimzi-topic-operator.yaml:  - "kafka.strimzi.io"
	topic-operator/04-Crd-kafkatopic.yaml:  name: kafkatopics.kafka.strimzi.io
	topic-operator/04-Crd-kafkatopic.yaml:  group: kafka.strimzi.io

** *_Cluster Operator_* (defined and installed earlier with link:https://github.com/skoussou/ocp-amq-streams-workshop/tree/master/install_and_examples_0/install/cluster-operator/040-Crd-kafka.yaml[install_and_examples_0/install/cluster-operator/040-Crd-kafka.yaml]) monitors for

	...
	spec:
	  group: kafka.strimzi.io
	  version: v1alpha1
	  scope: Namespaced
	  names:
	    kind: Kafka
	    listKind: KafkaList
	    singular: kafka
	    plural: kafkas
	...

** link:https://github.com/skoussou/ocp-amq-streams-workshop/tree/master/install_and_examples_0/examples/kafka/kafka-ephemeral.yaml[install_and_examples_0/examples/kafka/kafka-ephemeral.yaml] creates

	apiVersion: kafka.strimzi.io/v1alpha1
	kind: Kafka

** *_Cluster Operator_* reacts and installs the KAFKA cluster with 3 replicas, zookeeper cluster with 3 replicas
*** link:https://blog.openshift.com/introducing-the-operator-framework/[Introducing the Operator Framework: Building Apps on Kubernetes]
*** link:https://coreos.com/operators/[]
*** link:https://blog.openshift.com/make-a-kubernetes-operator-in-15-minutes-with-helm/[Make a Kubernetes Operator in 15 minutes with Helm]

* Resulting Object Resources Deployment
** *cluster-name-kafka* - StatefulSet which is in charge of managing the Kafka broker pods. 
** *cluster-name-zookeeper-nodes* - Secret with Zookeeper node keys. 
** *cluster-name-entity-operator* - Deployment with Topic and User Operators. This resource will be created only if Cluster Operator deployed Entity Operator and will monitor to deploy User and Topics

	$ oc get all
	NAME                                DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
	deploy/my-cluster-entity-operator   1         1         1            1           37m
	deploy/strimzi-cluster-operator     1         1         1            1           44m

	NAME                                       DESIRED   CURRENT   READY     AGE
	rs/my-cluster-entity-operator-686f6db58d   1         1         1         37m
	rs/strimzi-cluster-operator-696658566      1         1         1         44m

	NAME                                DESIRED   CURRENT   AGE
	statefulsets/my-cluster-kafka       3         3         39m
	statefulsets/my-cluster-zookeeper   3         3         41m

	NAME                                             READY     STATUS    RESTARTS   AGE
	po/my-cluster-entity-operator-686f6db58d-tzggx   3/3       Running   1          37m
	po/my-cluster-kafka-0                            2/2       Running   1          39m
	po/my-cluster-kafka-1                            2/2       Running   1          39m
	po/my-cluster-kafka-2                            2/2       Running   1          39m
	po/my-cluster-zookeeper-0                        2/2       Running   0          41m
	po/my-cluster-zookeeper-1                        2/2       Running   0          41m
	po/my-cluster-zookeeper-2                        2/2       Running   0          41m
	po/strimzi-cluster-operator-696658566-b9v5r      1/1       Running   0          44m

	NAME                              TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
	svc/my-cluster-kafka-bootstrap    ClusterIP   172.30.190.224   <none>        9091/TCP,9092/TCP,9093/TCP   39m
	svc/my-cluster-kafka-brokers      ClusterIP   None             <none>        9091/TCP,9092/TCP,9093/TCP   39m
	svc/my-cluster-zookeeper-client   ClusterIP   172.30.250.70    <none>        2181/TCP                     41m
	svc/my-cluster-zookeeper-nodes    ClusterIP   None             <none>        2181/TCP,2888/TCP,3888/TCP   41m

	[stkousso@stkousso ocp-amq-streams-workshop]$ oc get cm
	NAME                                      DATA      AGE
	my-cluster-entity-topic-operator-config   1         38m
	my-cluster-entity-user-operator-config    1         38m
	my-cluster-kafka-config                   1         39m
	my-cluster-zookeeper-config               1         41m

* Step 2: Expose KAFKA bootstrap servers to external, to OCP, clients
** Note the difference between KAFKA properties *brokers.list* and *bootstrap.serers* (see link:https://jaceklaskowski.gitbooks.io/apache-kafka/kafka-properties-bootstrap-servers.html[description here] is that the latter although can be a list of hosts:port a single one can be provided and the others will be discovered. In 
the examples we will use this method and hence we expose a single route of the service

	svc/my-cluster-kafka-bootstrap    ClusterIP   172.30.190.224   <none>        9091/TCP,9092/TCP,9093/TCP   39m

** expose service as follows

	oc expose service my-cluster-kafka-bootstrap

	$ oc describe route my-cluster-kafka-bootstrap 
	Name:			my-cluster-kafka-bootstrap
	Namespace:		amq-streams-ephemeral
	Created:		9 minutes ago
	Labels:			strimzi.io/cluster=my-cluster
				strimzi.io/kind=Kafka
				strimzi.io/name=my-cluster-kafka-bootstrap
	Annotations:		openshift.io/host.generated=true
	Requested Host:		my-cluster-kafka-bootstrap-amq-streams-ephemeral.192.168.42.249.nip.io
				  exposed on router router 9 minutes ago
	Path:			<none>
	TLS Termination:	<none>
	Insecure Policy:	<none>
	Endpoint Port:		replication

	Service:	my-cluster-kafka-bootstrap
	Weight:		100 (100%)
	Endpoints:	172.17.0.11:9092, 172.17.0.12:9092, 172.17.0.13:9092 + 6 more...


=== Configure Topic

Now that KAFKA cluster is running, create a topic to publish and subscribe from external client. Create the following *my-topic* Topic custom resource definition with 3 replicas and 3 partitions in my-cluster Kafka cluster:

* See link:README-amq-streams-ocp-configure.adoc[Configuration Workshop Activities] for additional Topic Creation/Configuration methods
* Create it by creating *KafkaTopic* CRD object

echo 'apiVersion: kafka.strimzi.io/v1alpha1
	kind: KafkaTopic
	metadata:
	 name: my-topic
	 labels:
	   strimzi.io/cluster: "my-cluster"
	spec:
	 partitions: 3
	 replicas: 3
	 config:
	   retention.ms: 7200000
	   segment.bytes: 1073741824' | oc create -f - -n amq-streams-ephemeral




=== Test 

==== Testing using an external application

* Ensure a route exists to the OCP Service *my-cluster-kafka-brokers*. Otherwise expose via TLS the service (console or oc tools)
* Go to client application https://github.com/skoussou/ocp-amq-streams-workshop/tree/master/clients/kafka-remote-client[kafka-remote-client]

	cd ./ocp-amq-streams-workshop/clients/kafka-remote-client

* As we are using Routes for external access to the cluster, we need the CA certs to enable TLS in the client. Extract the public certificate of the broker certification authority

	oc extract secret/my-cluster-cluster-ca-cert --keys=ca.crt --to=- > src/main/resources/ca.crt

* Import the trusted cert to a keystore

	keytool -import -trustcacerts -alias root -file src/main/resourcclients/camel-kafka-ocp-client/src/main/fabric8/build.ymles/ca.crt -keystore src/main/resources/keystore.jks -storepass password -noprompt

* Now you can run the Fuse application using the maven command:

	mvn -Drun.jvmArguments="-Dbootstrap.server=`oc get routes my-cluster-kafka-bootstrap -o=jsonpath='{.status.ingress[0].host}{"\n"}'`:443" clean package spring-boot:run


==== Testing using an OCP microservice application

* Step 1: Ensure the pre-reqs have been fullfilled and image *registry.access.redhat.com/jboss-fuse-6/fis-java-openshift:2.0* is in *openshift* namespace
* Step 2: Ensure cluster exists and 
** *my-topic* configured
** name of cluster is *my-cluster*
** service *my-cluster-kafka-bootstrap.amq-streams-ephemeral.svc* (exposing 9092) exists
* Step 3: install binary build

	oc login -u HOST user:password
        cd clients/camel-kafka-ocp-client
        oc create -f src/main/fabric8/imageStream.yml  -n amq-streams-ephemeral
	oc create -f src/main/fabric8/build.yml -n amq-streams-ephemeral
        mvn clean package
	oc start-build camel-kafka-demo-s2i --from-file=target/camel-kafka-demo-1.0.0-SNAPSHOT.jar
	oc new-app camel-kafka-demo

* Step 4: 

	oc get pods
	oc logs -f camel-kafka-demo-








examples/templates/topic-operator/topic-template.yaml






== Setup Resources

* Step 1: Create a Central Cluster Operator Namespece

	oc project amq-streams-ops

* Step 2:  Modify the installation files according to the namespace the Cluster Operator is going to be installed in.

	Either Download the latest C

	cd /home/stkousso/Stelios/sw11/KAFKA-AMQStreams/Distros/AMQ-Streams/1.0.0/install_and_examples_0/install
	sed -i 's/namespace: .*/namespace: amq-streams-ops/' install/cluster-operator/*RoleBinding*.yaml





== Install Cluster Operator

2.2. Cluster Operator		https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#cluster-operator-str
4.1. Cluster Operator		https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#assembly-operators-cluster-operator-str

* Step 1: Deploy the Cluster Operator

    cd /home/stkousso/Stelios/sw11/KAFKA-AMQStreams/Distros/AMQ-Streams/1.0.0/install_and_examples_0/
    oc apply -f install/cluster-operator -n _my-project_
    oc apply -f examples/templates/cluster-operator -n amq-streams-ops

== Install KAFKA Cluster


* Step 1: Deploying a persistent Kafka cluster to OpenShift

	cd /home/stkousso/Stelios/sw11/KAFKA-AMQStreams/Distros/AMQ-Streams/1.0.0/install_and_examples_0/
	oc apply -f examples/kafka/kafka-persistent.yaml


== Install KAFKA Connect Cluster

https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#kafka-connect-str


== Install KAFKA MirrorMaker Cluster

https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#kafka-mirror-maker-str


https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#deploying-the-topic-operator-using-the-cluster-operator-str



== Install Topic Operator

2.7. Topic Operator		https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#assembly-getting-started-topic-operator-str
4.2. Topic Operator		https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#deploying-the-topic-operator-str
5. Using the Topic Operator	https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#using-the-topic-operator-str

https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#deploying-the-topic-operator-using-the-cluster-operator-str

Configure it

https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#type-EntityTopicOperatorSpec-reference
https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#assembly-kafka-entity-operator-deployment-configuration-kafka


== Install User Operator


2.8. User Operator		https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#proc-deploying-the-user-operator-using-the-cluster-operator-str
4.3. User Operator		https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#assembly-user-operator-str
6. Using the User Operator	https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#assembly-using-the-user-operator-str

== Configure & Deploy KAFKA Cluster

https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#assembly-deployment-configuration-kafka-str
    3.1.1. Kafka and Zookeeper storage
    3.1.2. Replicas
    3.1.3. Kafka broker configuration
    3.1.4. Kafka broker listeners
    3.1.5. Authentication and Authorization
    3.1.6. Replicas
    3.1.7. Zookeeper configuration
    3.1.8. Entity Operator
    3.1.9. CPU and memory resources
    3.1.10. Logging
    3.1.11. Kafka rack awareness
    3.1.12. Healthchecks
    3.1.13. Prometheus metrics
    3.1.14. JVM Options
    3.1.15. Container images
    3.1.16. TLS sidecar
    3.1.17. Configuring pod scheduling
    3.1.18. Performing a rolling update of a Kafka cluster
    3.1.19. Performing a rolling update of a Zookeeper cluster
    3.1.20. Scaling clusters
    3.1.21. Deleting Kafka nodes manually
    3.1.22. Deleting Zookeeper nodes manually
    3.1.23. List of resources created as part of Kafka cluster



== Configure & Deploy KAFKA Connect Cluster

3.2. Kafka Connect cluster configuration
3.3. Kafka Connect cluster with Source2Image support


== Configure & Deploy KAFKA Mirror Maker 

3.4. Kafka Mirror Maker configuration

== Configure KAFKA Component Security

7. Security	https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#security-str




== Testing

== Deploy on OCP Clients

Deploying example clients: https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#deploying-example-clients-str


== Outside OCP Clients

https://developers.redhat.com/blog/2018/10/29/how-to-run-kafka-on-openshift-the-enterprise-kubernetes-with-amq-streams/








