= AMQ Streams (KAFKA) on OCP  - Installation Workshop Activities
Steps to install AMQ Streams 1.x on OCP 3.9+
:toc:


Considerations: * So if you have a centralized cluster operator, ????

== Ephemeral AQM Streams Installation
=== Setup Resources for Ephemeral AQM Streams Installation

* Step 1: Create a new Namespece

	oc new-project amq-streams-ephemeral
	oc login -u system:admin

* Step 2: Get the latest version of AMQ Streams CRDs
** Either Download the latest CRDs link:https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?downloadType=distributions&product=jboss.amq.streams[AMQ Streams ]
** [Select] The availble CRDs from this repository link:https://github.com/skoussou/ocp-amq-streams-workshop/tree/master/install_and_examples_0[install_and_examples_0]

* Step 3: Install the CRD (CustomResourceDefinition) objects for AMQ Streams
	cd install_and_examples_0
	sed -i 's/namespace: .*/namespace: amq-streams-ephemeral/' install/cluster-operator/*RoleBinding*.yaml
	oc apply -f install/cluster-operator/

** link:https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#ref-list-of-kafka-cluster-resources-deployment-configuration-kafka[List of resources created as part of Kafka cluster]


=== Install AMQ Streams

* Step 1: Install *KAFKA* object
	cd install_and_examples_0
	oc create -f examples/kafka/kafka-ephemeral.yaml

** The *OCP Operators* monitors for certain objects and takes action 
	grep -r kafka.strimzi.io
	cluster-operator/041-Crd-kafkaconnect.yaml:  name: kafkaconnects.kafka.strimzi.io
	cluster-operator/041-Crd-kafkaconnect.yaml:  group: kafka.strimzi.io
	cluster-operator/040-Crd-kafka.yaml:  name: kafkas.kafka.strimzi.io
	cluster-operator/040-Crd-kafka.yaml:  group: kafka.strimzi.io
	cluster-operator/042-Crd-kafkaconnects2i.yaml:  name: kafkaconnects2is.kafka.strimzi.io
	cluster-operator/042-Crd-kafkaconnects2i.yaml:  group: kafka.strimzi.io
	cluster-operator/043-Crd-kafkatopic.yaml:  name: kafkatopics.kafka.strimzi.io
	cluster-operator/043-Crd-kafkatopic.yaml:  group: kafka.strimzi.io
	cluster-operator/031-ClusterRole-strimzi-entity-operator.yaml:  - kafka.strimzi.io
	cluster-operator/031-ClusterRole-strimzi-entity-operator.yaml:  - kafka.strimzi.io
	cluster-operator/045-Crd-kafkamirrormaker.yaml:  name: kafkamirrormakers.kafka.strimzi.io
	cluster-operator/045-Crd-kafkamirrormaker.yaml:  group: kafka.strimzi.io
	cluster-operator/020-ClusterRole-strimzi-cluster-operator-role.yaml:  - kafka.strimzi.io
	cluster-operator/032-ClusterRole-strimzi-topic-operator.yaml:  - kafka.strimzi.io
	cluster-operator/044-Crd-kafkauser.yaml:  name: kafkausers.kafka.strimzi.io
	cluster-operator/044-Crd-kafkauser.yaml:  group: kafka.strimzi.io
	user-operator/02-Role-strimzi-user-operator.yaml:  - "kafka.strimzi.io"
	user-operator/04-Crd-kafkauser.yaml:  name: kafkausers.kafka.strimzi.io
	user-operator/04-Crd-kafkauser.yaml:  group: kafka.strimzi.io
	topic-operator/02-Role-strimzi-topic-operator.yaml:  - "kafka.strimzi.io"
	topic-operator/04-Crd-kafkatopic.yaml:  name: kafkatopics.kafka.strimzi.io
	topic-operator/04-Crd-kafkatopic.yaml:  group: kafka.strimzi.io

** *_Cluster Operator_* (defined and installed earlier with link:https://github.com/skoussou/ocp-amq-streams-workshop/tree/master/install_and_examples_0[/install/cluster-operator/040-Crd-kafka.yaml[install_and_examples_0[/install/cluster-operator/040-Crd-kafka.yaml]) monitors for
	...
	spec:
	  group: kafka.strimzi.io
	  version: v1alpha1
	  scope: Namespaced
	  names:
	    kind: Kafka
	    listKind: KafkaList
	    singular: kafka
	    plural: kafkas
	...

** link:https://github.com/skoussou/ocp-amq-streams-workshop/tree/master/install_and_examples_0/examples/kafka/kafka-ephemeral.yaml[install_and_examples_0/examples/kafka/kafka-ephemeral.yaml] creates
	apiVersion: kafka.strimzi.io/v1alpha1
	kind: Kafka

** *_Cluster Operator_* reacts and installs the KAFKA, zookeeper
*** link:https://blog.openshift.com/introducing-the-operator-framework/[Introducing the Operator Framework: Building Apps on Kubernetes]
*** link:https://coreos.com/operators/[]
*** link:https://blog.openshift.com/make-a-kubernetes-operator-in-15-minutes-with-helm/[Make a Kubernetes Operator in 15 minutes with Helm]

* Resulting Object Resources Deployment
** *cluster-name-kafka* - StatefulSet which is in charge of managing the Kafka broker pods. 
** *cluster-name-zookeeper-nodes* - Secret with Zookeeper node keys. 
** *cluster-name-entity-operator* - Deployment with Topic and User Operators. This resource will be created only if Cluster Operator deployed Entity Operator and will monitor to deploy User and Topics


=== Configure Topic

    Now that KAFKA cluster is running, create a topic to publish and subscribe from external client. Create the following *my-topic* Topic custom resource definition with 3 replicas and 3 partitions in my-cluster Kafka cluster:

echo 'apiVersion: kafka.strimzi.io/v1alpha1
	kind: KafkaTopic
	metadata:
	 name: my-topic
	 labels:
	   strimzi.io/cluster: "my-cluster"
	spec:
	 partitions: 3
	 replicas: 3
	 config:
	   retention.ms: 7200000
	   segment.bytes: 1073741824
	EOF | ' | oc create -f - -n amq-streams-ephemeral






== Setup Resources

* Step 1: Create a Central Cluster Operator Namespece

	oc project amq-streams-ops

* Step 2:  Modify the installation files according to the namespace the Cluster Operator is going to be installed in.

	Either Download the latest C

	cd /home/stkousso/Stelios/sw11/KAFKA-AMQStreams/Distros/AMQ-Streams/1.0.0/install_and_examples_0/install
	sed -i 's/namespace: .*/namespace: amq-streams-ops/' install/cluster-operator/*RoleBinding*.yaml





== Install Cluster Operator

2.2. Cluster Operator		https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#cluster-operator-str
4.1. Cluster Operator		https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#assembly-operators-cluster-operator-str

* Step 1: Deploy the Cluster Operator

    cd /home/stkousso/Stelios/sw11/KAFKA-AMQStreams/Distros/AMQ-Streams/1.0.0/install_and_examples_0/
    oc apply -f install/cluster-operator -n _my-project_
    oc apply -f examples/templates/cluster-operator -n amq-streams-ops

== Install KAFKA Cluster


* Step 1: Deploying a persistent Kafka cluster to OpenShift

	cd /home/stkousso/Stelios/sw11/KAFKA-AMQStreams/Distros/AMQ-Streams/1.0.0/install_and_examples_0/
	oc apply -f examples/kafka/kafka-persistent.yaml


== Install KAFKA Connect Cluster

https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#kafka-connect-str


== Install KAFKA MirrorMaker Cluster

https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#kafka-mirror-maker-str


https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#deploying-the-topic-operator-using-the-cluster-operator-str



== Install Topic Operator

2.7. Topic Operator		https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#assembly-getting-started-topic-operator-str
4.2. Topic Operator		https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#deploying-the-topic-operator-str
5. Using the Topic Operator	https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#using-the-topic-operator-str

https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#deploying-the-topic-operator-using-the-cluster-operator-str

Configure it

https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#type-EntityTopicOperatorSpec-reference
https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#assembly-kafka-entity-operator-deployment-configuration-kafka


== Install User Operator


2.8. User Operator		https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#proc-deploying-the-user-operator-using-the-cluster-operator-str
4.3. User Operator		https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#assembly-user-operator-str
6. Using the User Operator	https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#assembly-using-the-user-operator-str

== Configure & Deploy KAFKA Cluster

https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#assembly-deployment-configuration-kafka-str
    3.1.1. Kafka and Zookeeper storage
    3.1.2. Replicas
    3.1.3. Kafka broker configuration
    3.1.4. Kafka broker listeners
    3.1.5. Authentication and Authorization
    3.1.6. Replicas
    3.1.7. Zookeeper configuration
    3.1.8. Entity Operator
    3.1.9. CPU and memory resources
    3.1.10. Logging
    3.1.11. Kafka rack awareness
    3.1.12. Healthchecks
    3.1.13. Prometheus metrics
    3.1.14. JVM Options
    3.1.15. Container images
    3.1.16. TLS sidecar
    3.1.17. Configuring pod scheduling
    3.1.18. Performing a rolling update of a Kafka cluster
    3.1.19. Performing a rolling update of a Zookeeper cluster
    3.1.20. Scaling clusters
    3.1.21. Deleting Kafka nodes manually
    3.1.22. Deleting Zookeeper nodes manually
    3.1.23. List of resources created as part of Kafka cluster



== Configure & Deploy KAFKA Connect Cluster

3.2. Kafka Connect cluster configuration
3.3. Kafka Connect cluster with Source2Image support


== Configure & Deploy KAFKA Mirror Maker 

3.4. Kafka Mirror Maker configuration

== Configure KAFKA Component Security

7. Security	https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#security-str




== Testing

== Deploy on OCP Clients

Deploying example clients: https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/#deploying-example-clients-str


== Outside OCP Clients

https://developers.redhat.com/blog/2018/10/29/how-to-run-kafka-on-openshift-the-enterprise-kubernetes-with-amq-streams/








