= AMQ Streams (KAFKA) on OCP Workshop
Steps to setup AMQ Streams 1.x on OCP 3.9+  and run some examples
:toc:


== Scope

* Installation and overall view of Kafka on OCP
* Management tools included in AMQ streams in order to 
** create, 
** read, 
** update
** delete topic in kafka (via UI or command line tool)
* How to manage AMQ Streams (KAFKA) cluster
* overall view of monitoring tool included in AMQ streams
* security (kerberos, oauth2).
* Architecture choices (single central cluster, collaborating projects, topic discovery, etc.)

== Environment Pre-Requisites
* Storage Available
* Cluster Topology/Networking
* ImageStreams/Images in cluster
* Security/Auhorization
**  A user with cluster-admin role needs to be used, for example, system:admin. 

== Tools Pre-requisites
* oc tools
* Download link:https://access.redhat.com/node/3596931/423/1[install_and_examples.zip]
* Add to OCP Cluster Registry the following images
** registry.access.redhat.com/amqstreams-1/amqstreams10-clusteroperator-openshift:1.0.0
** registry.access.redhat.com/amqstreams-1/amqstreams10-useroperator-openshift:1.0.0
** registry.access.redhat.com/amqstreams-1/amqstreams10-topicoperator-openshift:1.0.0
** strimzi/kafka-mirror-maker:latest
* Ensure imagestreams are installed in *openshift* namespace
** clone https://github.com/openshift/library
** Run a script to install *official* imagestreams in *openshift* namespace such as this link:https://github.com/skoussou/ocp-amq-streams-workshop/blob/master/scripts/install-official-is-imagestreams.sh[install-official-is-imagestreams.sh] as cluster admin
** To avoid minishift issues with registry authentication download 3.10 images:https://github.com/minishift/minishift/blob/master/addons/xpaas/v3.10/xpaas-streams/fis-image-streams.json also available at  link:https://github.com/skoussou/ocp-amq-streams-workshop/blob/master/env/minishift-is.json[env/minishift-is.json]
** Image to be present in registry registry.access.redhat.com/jboss-fuse-6/fis-java-openshift:2.0

== AMQ Streams on OCP Components & Features

=== Kafka Key Features

* Scalability and performance
** Designed for horizontal scalability 

* Message ordering guarantee
** At partition level 

* Message rewind/replay
** "Long term" storage
** Allows to reconstruct application state by replaying the messages
** Combined with compacted topics allows to use Kafka as key-value store 

=== AMQ Streams Components

* Cluster Operator: Responsible for deploying and managing Apache Kafka clusters within OpenShift cluster. 
** Cluster Operator watches the following resources:
*** A *Kafka* resource for the Kafka cluster.
*** A *KafkaConnect* resource for the Kafka Connect cluster.
*** A *KafkaConnectS2I* resource for the Kafka Connect cluster with Source2Image support. 
** To deploy a Kafka cluster, a *Kafka resource* with the cluster configuration has to be created within the OpenShift cluster. Based on what is declared inside of the Kafka resource, the Cluster Operator deploys a corresponding Kafka cluste
* Topic Operator: Responsible for managing Kafka topics within a Kafka cluster running within OpenShift cluster. 
* User Operator: Responsible for managing Kafka users within a Kafka cluster running within OpenShift cluster. 

== Create Enironment

=== Minishift

	minishift profile set amq-streams-workshop

	$ minishift profile list
	- amq-streams-workshop	Does Not Exist	(Active)
	- minishift		Stopped

	minishift config set cpus 2
	minishift config set memory 6144
	minishift addons disable anyuid

	minishift start

== Workshop Activities

* link:README-amq-streams-ocp-install.adoc[Installation Workshop Activities]
* link:README-amq-streams-ocp-configure.adoc[Configuration Workshop Activities]
* link:README-amq-streams-ocp-workwithcluster.adoc[Self-Service Dev-Team Workshop Activities ]


== Additional Resources

From  RHTE Tom and Jakub set up some material on GitHub like this one https://github.com/tombentley/rhte-2018 and https://github.com/scholzj/rhte-prague-2018

Jakub should also have a repo with demo for the support internal training

there is also this one from me for the RHOSD https://github.com/ppatierno/rh-osd-2018


